// Generated by ReScript, PLEASE EDIT WITH CARE


var callWithFinally = ((fn, finallyCb) => {
    try {
      return fn()
    } finally {
      finallyCb()
    }
  });

var context = {
  r: undefined,
  u: undefined,
  q: [],
  v: 0,
  p: undefined,
  n: undefined
};

context.n = (function () {
    var iterator = context.q;
    context.q = [];
    for(var effectsIdx = 0 ,effectsIdx_finish = iterator.length; effectsIdx < effectsIdx_finish; ++effectsIdx){
      var effects = iterator[effectsIdx];
      for(var effectIdx = 0 ,effectIdx_finish = effects.length; effectIdx < effectIdx_finish; ++effectIdx){
        var effect = effects[effectIdx];
        effect();
      }
    }
  });

function notify() {
  context.n();
}

function wrapNotify(fn) {
  var prevNotify = context.n;
  context.n = (function () {
      fn(prevNotify);
    });
}

function make(initial) {
  var valueAct = {
    a: initial,
    v: -1,
    e: [],
    g: undefined,
    s: undefined
  };
  var valueAct$1 = (function (__x) {
        return __x;
      })(valueAct);
  valueAct$1.g = (function () {
      if (valueAct$1.v !== context.v) {
        valueAct$1.v = context.v;
        var match = context.u;
        var match$1 = context.r;
        if (match !== undefined) {
          valueAct$1.e.splice(valueAct$1.e.indexOf(match), 1);
        } else if (match$1 !== undefined) {
          valueAct$1.e.push(match$1);
        }
        
      }
      var pubs = context.p;
      if (pubs !== undefined) {
        pubs.push({
              a: valueAct$1,
              s: valueAct$1.a
            });
      }
      return valueAct$1.a;
    });
  valueAct$1.s = (function (state) {
      valueAct$1.a = state;
      if (context.q.push(valueAct$1.e) === 1) {
        Promise.resolve().then(notify);
      }
      valueAct$1.e = [];
      if (valueAct$1.v !== context.v) {
        valueAct$1.v = context.v;
        var match = context.u;
        var match$1 = context.r;
        if (match !== undefined) {
          valueAct$1.e.splice(valueAct$1.e.indexOf(match), 1);
        } else if (match$1 !== undefined) {
          valueAct$1.e.push(match$1);
        }
        
      }
      var pubs = context.p;
      if (pubs !== undefined) {
        pubs.push({
              a: valueAct$1,
              s: valueAct$1.a
            });
        return ;
      }
      
    });
  return valueAct;
}

function computed(maybeEqualityCheck, fn) {
  var computedAct = {
    a: undefined,
    v: -1,
    p: [],
    g: undefined,
    s: (function (prim) {
        
      })
  };
  var computedAct$1 = (function (__x) {
        return __x;
      })(computedAct);
  computedAct$1.g = (function () {
      if (computedAct$1.v !== context.v || context.r === undefined) {
        var computedPubs = computedAct$1.p;
        var prevPubs = context.p;
        context.p = undefined;
        var isEmptyComputedPubs = computedPubs.length === 0;
        if (isEmptyComputedPubs || computedPubs.some(function (el) {
                return el.a.g() !== el.s;
              })) {
          var newPubs = isEmptyComputedPubs ? computedPubs : [];
          context.p = newPubs;
          computedAct$1.p = newPubs;
          var newState = fn();
          if (computedAct$1.v === -1 || (
              maybeEqualityCheck !== undefined ? !maybeEqualityCheck(computedAct$1.a, newState) : true
            )) {
            computedAct$1.a = newState;
          }
          
        }
        context.p = prevPubs;
        computedAct$1.v = context.v;
      }
      var pubs = context.p;
      if (pubs !== undefined) {
        pubs.push({
              a: computedAct$1,
              s: computedAct$1.a
            });
      }
      return computedAct$1.a;
    });
  return computedAct;
}

function subscribe(act, cb) {
  var subscribtionContext = {
    q: cb,
    s: cb
  };
  var effect = function () {
    if (subscribtionContext.q === context.q) {
      return ;
    }
    subscribtionContext.q = context.q;
    context.v = context.v + 1;
    var prevRoot = context.r;
    context.r = effect;
    callWithFinally((function () {
            var calculatedState = act.g();
            if (subscribtionContext.s !== calculatedState) {
              subscribtionContext.s = calculatedState;
              return cb(calculatedState);
            }
            
          }), (function () {
            context.r = prevRoot;
          }));
  };
  effect();
  return function () {
    context.v = context.v + 1;
    context.u = effect;
    act.g();
    context.u = undefined;
  };
}

export {
  make ,
  computed ,
  subscribe ,
  notify ,
  wrapNotify ,
}
/*  Not a pure module */
